
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef SERVEROBJECT_H
#define SERVEROBJECT_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 serverobject_valueRangeTest (UNS8 typeValue, void * value);
const indextable * serverobject_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data serverobject_Data;
extern INTEGER32 can_roll;		/* Mapped at index 0x6064, subindex 0x00*/
extern INTEGER32 can_pitch;		/* Mapped at index 0x6069, subindex 0x00*/
extern INTEGER32 Velocity_actual_value;		/* Mapped at index 0x606C, subindex 0x00*/

#endif // SERVEROBJECT_H
