
/* File generated by gen_cfile.py. Should not be modified. */

#include "serverobject.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS16 Controlword = 0x0;		/* Mapped at index 0x6040, subindex 0x00 */
UNS16 Statusword = 0x0;		/* Mapped at index 0x6041, subindex 0x00 */
INTEGER8 Modes_of_operation = 0x0;		/* Mapped at index 0x6060, subindex 0x00 */
INTEGER8 Modes_of_operation_display = 0x0;		/* Mapped at index 0x6061, subindex 0x00 */
INTEGER32 Position_demannd_value = 0x0;		/* Mapped at index 0x6062, subindex 0x00 */
INTEGER32 can_roll = 0x0;		/* Mapped at index 0x6064, subindex 0x00 *///这里开始我用做x轴角度
UNS32 Maximal_following_error = 0x0;		/* Mapped at index 0x6065, subindex 0x00 */
UNS32 Position_window = 0x0;		/* Mapped at index 0x6067, subindex 0x00 */
UNS16 Position_window_time = 0x0;		/* Mapped at index 0x6068, subindex 0x00 */
INTEGER32 can_pitch = 0x0;		/* Mapped at index 0x6069, subindex 0x00 *///这里开始我用做y轴角度
INTEGER32 Velocity_demand_value = 0x0;		/* Mapped at index 0x606B, subindex 0x00 */
INTEGER32 can_yaw = 0x0;		/* Mapped at index 0x606C, subindex 0x00 *///这里开始我用做z轴角度
INTEGER16 Current_actual_value = 0x0;		/* Mapped at index 0x6078, subindex 0x00 */
INTEGER32 Target_position = 0x0;		/* Mapped at index 0x607A, subindex 0x00 */
INTEGER32 Home_offset = 0x0;		/* Mapped at index 0x607C, subindex 0x00 */
INTEGER32 Software_position_limit_Minimal_position_limit = 0x0;		/* Mapped at index 0x607D, subindex 0x01 */
INTEGER32 Software_position_limit_Maximal_position_limit = 0x0;		/* Mapped at index 0x607D, subindex 0x02 */
UNS32 Maximal_profile_velocity = 0x0;		/* Mapped at index 0x607F, subindex 0x00 */
UNS32 Profile_velocity = 0x0;		/* Mapped at index 0x6081, subindex 0x00 */
UNS32 Profile_acceleration = 0x0;		/* Mapped at index 0x6083, subindex 0x00 */
UNS32 Profile_deceleration = 0x0;		/* Mapped at index 0x6084, subindex 0x00 */
UNS32 Quick_stop_deceleration = 0x0;		/* Mapped at index 0x6085, subindex 0x00 */
INTEGER16 Motion_profile_type = 0x0;		/* Mapped at index 0x6086, subindex 0x00 */
INTEGER8 Position_notation_index = 0x0;		/* Mapped at index 0x6089, subindex 0x00 */
REAL32 Position_dimention_index = 0.000000;		/* Mapped at index 0x608A, subindex 0x00 */
INTEGER8 Velocity_notation_index = 0x0;		/* Mapped at index 0x608B, subindex 0x00 */
REAL32 Velocity_dimention_index = 0.000000;		/* Mapped at index 0x608C, subindex 0x00 */
INTEGER8 Acceleraion_notation_index = 0x0;		/* Mapped at index 0x608D, subindex 0x00 */
REAL32 Acceleraion_dimention_index = 0.000000;		/* Mapped at index 0x608E, subindex 0x00 */
INTEGER8 Homing_method = 0x0;		/* Mapped at index 0x6098, subindex 0x00 */
UNS32 Homing_speeds_Speed_for_switch_search = 0x0;		/* Mapped at index 0x6099, subindex 0x01 */
UNS32 Homing_speeds_Speed_for_zero_search = 0x0;		/* Mapped at index 0x6099, subindex 0x02 */
UNS32 Homing_acceleration = 0x0;		/* Mapped at index 0x609A, subindex 0x00 */
INTEGER16 Current_control_parameter_set_Current_regulator_P_gain = 0x0;		/* Mapped at index 0x60F6, subindex 0x01 */
INTEGER16 Current_control_parameter_set_Current_regulator_I_gain = 0x0;		/* Mapped at index 0x60F6, subindex 0x02 */
INTEGER16 Velocity_control_parameter_set_Velocity_regulator_P_gain = 0x0;		/* Mapped at index 0x60F9, subindex 0x01 */
INTEGER16 Velocity_control_parameter_set_Velocity_regulator_I_gain = 0x0;		/* Mapped at index 0x60F9, subindex 0x02 */
INTEGER16 Position_control_parameter_set_Position_regulator_P_gain = 0x0;		/* Mapped at index 0x60FB, subindex 0x01 */
INTEGER16 Position_control_parameter_set_Position_regulator_I_gain = 0x0;		/* Mapped at index 0x60FB, subindex 0x02 */
INTEGER16 Position_control_parameter_set_Position_regulator_D_gain = 0x0;		/* Mapped at index 0x60FB, subindex 0x03 */
UNS16 Position_control_parameter_set_Velocity_feed_forward_factor = 0x0;		/* Mapped at index 0x60FB, subindex 0x04 */
UNS16 Position_control_parameter_set_Acceleration_feed_forward_factor = 0x0;		/* Mapped at index 0x60FB, subindex 0x05 */
INTEGER32 Target_velocity = 0x0;		/* Mapped at index 0x60FF, subindex 0x00 */
UNS16 Motor_type = 0x0;		/* Mapped at index 0x6402, subindex 0x00 */
UNS16 Motor_data_Continous_current_limit = 0x0;		/* Mapped at index 0x6410, subindex 0x01 */
UNS16 Motor_data_Output_current_limit = 0x0;		/* Mapped at index 0x6410, subindex 0x02 */
UNS8 Motor_data_Pole_pair_number = 0x0;		/* Mapped at index 0x6410, subindex 0x03 */
UNS16 Motor_data_Maximal_speed_in_current_mode = 0x0;		/* Mapped at index 0x6410, subindex 0x04 */
UNS16 Motor_data_Thermal_time_constant_winding = 0x0;		/* Mapped at index 0x6410, subindex 0x05 */
UNS32 Supported_drive_modes = 0x0;		/* Mapped at index 0x6502, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 serverobject_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 serverobject_bDeviceNodeId = 0x01;
const UNS8 NodeId = 0x01;
/********* *****************************************************************/
/* Array of message processing information */

const UNS8 serverobject_iam_a_slave = 1;

TIMER_HANDLE serverobject_heartBeatTimers[1] = {TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 serverobject_obj1000 = 0x1;	/* 0 */
                    subindex serverobject_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&serverobject_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 serverobject_obj1001 = 0x2;	/* 0 */
                    subindex serverobject_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&serverobject_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 serverobject_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 serverobject_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex serverobject_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&serverobject_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 serverobject_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 serverobject_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 serverobject_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 serverobject_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 serverobject_obj1014 = 0x80+NodeId;	/* 128+serverobject_bDeviceNodeId */
                    subindex serverobject_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1014, NULL }
                     };

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 serverobject_highestSubIndex_obj1016 = 1; /* number of subindex - 1*/
                    UNS32 serverobject_obj1016[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex serverobject_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj1016, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1016[0], NULL }
                     };

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 serverobject_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 serverobject_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 serverobject_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 serverobject_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 serverobject_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 serverobject_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex serverobject_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&serverobject_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&serverobject_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&serverobject_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&serverobject_obj1018_Serial_Number, NULL }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 serverobject_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 serverobject_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600+NodeId;	/* 1536 */
                    UNS32 serverobject_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580+NodeId;	/* 1408 */
                    subindex serverobject_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj1200, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&serverobject_obj1200_COB_ID_Client_to_Server_Receive_SDO, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&serverobject_obj1200_COB_ID_Server_to_Client_Transmit_SDO, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 serverobject_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 serverobject_obj1400_COB_ID_used_by_PDO = 0x200+NodeId;	/* 512 */
                    UNS8 serverobject_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 serverobject_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 serverobject_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 serverobject_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 serverobject_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex serverobject_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&serverobject_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&serverobject_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1400_SYNC_start_value, NULL }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 serverobject_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 serverobject_obj1401_COB_ID_used_by_PDO = 0x300+NodeId;	/* 768 */
                    UNS8 serverobject_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 serverobject_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 serverobject_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 serverobject_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 serverobject_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex serverobject_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj1401, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1401_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1401_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&serverobject_obj1401_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1401_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&serverobject_obj1401_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1401_SYNC_start_value, NULL }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 serverobject_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 serverobject_obj1402_COB_ID_used_by_PDO = 0x400+NodeId;	/* 1024 */
                    UNS8 serverobject_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 serverobject_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 serverobject_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 serverobject_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 serverobject_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex serverobject_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj1402, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1402_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1402_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&serverobject_obj1402_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1402_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&serverobject_obj1402_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1402_SYNC_start_value, NULL }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 serverobject_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 serverobject_obj1403_COB_ID_used_by_PDO = 0x500+NodeId;	/* 1280 */
                    UNS8 serverobject_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 serverobject_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 serverobject_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 serverobject_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 serverobject_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex serverobject_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj1403, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1403_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1403_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&serverobject_obj1403_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1403_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&serverobject_obj1403_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1403_SYNC_start_value, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 serverobject_highestSubIndex_obj1600 = 8; /* number of subindex - 1*/
                    UNS32 serverobject_obj1600[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex serverobject_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj1600, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1600[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1600[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1600[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1600[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1600[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1600[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1600[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1600[7], NULL }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 serverobject_highestSubIndex_obj1601 = 8; /* number of subindex - 1*/
                    UNS32 serverobject_obj1601[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex serverobject_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj1601, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1601[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1601[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1601[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1601[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1601[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1601[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1601[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1601[7], NULL }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 serverobject_highestSubIndex_obj1602 = 8; /* number of subindex - 1*/
                    UNS32 serverobject_obj1602[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex serverobject_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj1602, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1602[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1602[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1602[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1602[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1602[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1602[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1602[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1602[7], NULL }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 serverobject_highestSubIndex_obj1603 = 8; /* number of subindex - 1*/
                    UNS32 serverobject_obj1603[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex serverobject_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj1603, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1603[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1603[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1603[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1603[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1603[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1603[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1603[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1603[7], NULL }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 serverobject_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 serverobject_obj1800_COB_ID_used_by_PDO = 0x180+NodeId;	/* 384 */
                    UNS8 serverobject_obj1800_Transmission_Type = 0x0;	/* 0 */
                    UNS16 serverobject_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 serverobject_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 serverobject_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 serverobject_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    subindex serverobject_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&serverobject_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&serverobject_obj1800_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1800_SYNC_start_value, NULL }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 serverobject_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 serverobject_obj1801_COB_ID_used_by_PDO = 0x280+NodeId;	/* 640 */
                    UNS8 serverobject_obj1801_Transmission_Type = 0x0;	/* 0 */
                    UNS16 serverobject_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 serverobject_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 serverobject_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 serverobject_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    subindex serverobject_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj1801, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1801_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1801_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&serverobject_obj1801_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1801_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&serverobject_obj1801_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1801_SYNC_start_value, NULL }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 serverobject_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 serverobject_obj1802_COB_ID_used_by_PDO = 0x380+NodeId;	/* 896 */
                    UNS8 serverobject_obj1802_Transmission_Type = 0x0;	/* 0 */
                    UNS16 serverobject_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 serverobject_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 serverobject_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 serverobject_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    subindex serverobject_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj1802, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1802_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1802_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&serverobject_obj1802_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1802_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&serverobject_obj1802_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1802_SYNC_start_value, NULL }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 serverobject_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 serverobject_obj1803_COB_ID_used_by_PDO = 0x480+NodeId;	/* 1152 */
                    UNS8 serverobject_obj1803_Transmission_Type = 0x0;	/* 0 */
                    UNS16 serverobject_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 serverobject_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 serverobject_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 serverobject_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    subindex serverobject_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj1803, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1803_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1803_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&serverobject_obj1803_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1803_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&serverobject_obj1803_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_obj1803_SYNC_start_value, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 serverobject_highestSubIndex_obj1A00 = 8; /* number of subindex - 1*/
                    UNS32 serverobject_obj1A00[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex serverobject_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A00[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A00[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A00[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A00[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A00[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A00[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A00[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A00[7], NULL }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 serverobject_highestSubIndex_obj1A01 = 8; /* number of subindex - 1*/
                    UNS32 serverobject_obj1A01[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex serverobject_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj1A01, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A01[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A01[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A01[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A01[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A01[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A01[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A01[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A01[7], NULL }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 serverobject_highestSubIndex_obj1A02 = 8; /* number of subindex - 1*/
                    UNS32 serverobject_obj1A02[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex serverobject_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj1A02, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A02[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A02[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A02[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A02[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A02[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A02[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A02[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A02[7], NULL }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 serverobject_highestSubIndex_obj1A03 = 8; /* number of subindex - 1*/
                    UNS32 serverobject_obj1A03[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex serverobject_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj1A03, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A03[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A03[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A03[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A03[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A03[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A03[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A03[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&serverobject_obj1A03[7], NULL }
                     };

/* index 0x6040 :   Mapped variable Controlword */
                    subindex serverobject_Index6040[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Controlword, NULL }
                     };

/* index 0x6041 :   Mapped variable Statusword */
                    subindex serverobject_Index6041[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&Statusword, NULL }
                     };

/* index 0x6060 :   Mapped variable Modes of operation */
                    subindex serverobject_Index6060[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&Modes_of_operation, NULL }
                     };

/* index 0x6061 :   Mapped variable Modes of operation display */
                    subindex serverobject_Index6061[] = 
                     {
                       { RO, int8, sizeof (INTEGER8), (void*)&Modes_of_operation_display, NULL }
                     };

/* index 0x6062 :   Mapped variable Position demannd value */
                    subindex serverobject_Index6062[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Position_demannd_value, NULL }
                     };

/* index 0x6064 :   Mapped variable Position actual value */
                    subindex serverobject_Index6064[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&can_roll, NULL }
                     };

/* index 0x6065 :   Mapped variable Maximal following error */
                    subindex serverobject_Index6065[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Maximal_following_error, NULL }
                     };

/* index 0x6067 :   Mapped variable Position window */
                    subindex serverobject_Index6067[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Position_window, NULL }
                     };

/* index 0x6068 :   Mapped variable Position window time */
                    subindex serverobject_Index6068[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Position_window_time, NULL }
                     };

/* index 0x6069 :   Mapped variable Velocity sensor actual value */
                    subindex serverobject_Index6069[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&can_pitch, NULL }
                     };

/* index 0x606B :   Mapped variable Velocity demand value */
                    subindex serverobject_Index606B[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&Velocity_demand_value, NULL }
                     };

/* index 0x606C :   Mapped variable Velocity actual value */
                    subindex serverobject_Index606C[] = 
                     {
                       { RO, int32, sizeof (INTEGER32), (void*)&can_yaw, NULL }
                     };

/* index 0x6078 :   Mapped variable Current actual value */
                    subindex serverobject_Index6078[] = 
                     {
                       { RO, int16, sizeof (INTEGER16), (void*)&Current_actual_value, NULL }
                     };

/* index 0x607A :   Mapped variable Target position */
                    subindex serverobject_Index607A[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Target_position, NULL }
                     };

/* index 0x607C :   Mapped variable Home offset */
                    subindex serverobject_Index607C[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Home_offset, NULL }
                     };

/* index 0x607D :   Mapped variable Software position limit */
                    UNS8 serverobject_highestSubIndex_obj607D = 2; /* number of subindex - 1*/
                    subindex serverobject_Index607D[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj607D, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&Software_position_limit_Minimal_position_limit, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&Software_position_limit_Maximal_position_limit, NULL }
                     };

/* index 0x607F :   Mapped variable Maximal profile velocity */
                    subindex serverobject_Index607F[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Maximal_profile_velocity, NULL }
                     };

/* index 0x6081 :   Mapped variable Profile velocity */
                    subindex serverobject_Index6081[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Profile_velocity, NULL }
                     };

/* index 0x6083 :   Mapped variable Profile acceleration */
                    subindex serverobject_Index6083[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Profile_acceleration, NULL }
                     };

/* index 0x6084 :   Mapped variable Profile deceleration */
                    subindex serverobject_Index6084[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Profile_deceleration, NULL }
                     };

/* index 0x6085 :   Mapped variable Quick stop deceleration */
                    subindex serverobject_Index6085[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Quick_stop_deceleration, NULL }
                     };

/* index 0x6086 :   Mapped variable Motion profile type */
                    subindex serverobject_Index6086[] = 
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&Motion_profile_type, NULL }
                     };

/* index 0x6089 :   Mapped variable Position notation index */
                    subindex serverobject_Index6089[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&Position_notation_index, NULL }
                     };

/* index 0x608A :   Mapped variable Position dimention index */
                    subindex serverobject_Index608A[] = 
                     {
                       { RW, real32, sizeof (REAL32), (void*)&Position_dimention_index, NULL }
                     };

/* index 0x608B :   Mapped variable Velocity notation index */
                    subindex serverobject_Index608B[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&Velocity_notation_index, NULL }
                     };

/* index 0x608C :   Mapped variable Velocity dimention index */
                    subindex serverobject_Index608C[] = 
                     {
                       { RW, real32, sizeof (REAL32), (void*)&Velocity_dimention_index, NULL }
                     };

/* index 0x608D :   Mapped variable Acceleraion notation index */
                    subindex serverobject_Index608D[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&Acceleraion_notation_index, NULL }
                     };

/* index 0x608E :   Mapped variable Acceleraion dimention index */
                    subindex serverobject_Index608E[] = 
                     {
                       { RW, real32, sizeof (REAL32), (void*)&Acceleraion_dimention_index, NULL }
                     };

/* index 0x6098 :   Mapped variable Homing method */
                    subindex serverobject_Index6098[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&Homing_method, NULL }
                     };

/* index 0x6099 :   Mapped variable Homing speeds */
                    UNS8 serverobject_highestSubIndex_obj6099 = 2; /* number of subindex - 1*/
                    subindex serverobject_Index6099[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj6099, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_speeds_Speed_for_switch_search, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_speeds_Speed_for_zero_search, NULL }
                     };

/* index 0x609A :   Mapped variable Homing acceleration */
                    subindex serverobject_Index609A[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Homing_acceleration, NULL }
                     };

/* index 0x60F6 :   Mapped variable Current control parameter set */
                    UNS8 serverobject_highestSubIndex_obj60F6 = 2; /* number of subindex - 1*/
                    subindex serverobject_Index60F6[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj60F6, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Current_control_parameter_set_Current_regulator_P_gain, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Current_control_parameter_set_Current_regulator_I_gain, NULL }
                     };

/* index 0x60F9 :   Mapped variable Velocity control parameter set */
                    UNS8 serverobject_highestSubIndex_obj60F9 = 2; /* number of subindex - 1*/
                    subindex serverobject_Index60F9[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj60F9, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Velocity_control_parameter_set_Velocity_regulator_P_gain, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Velocity_control_parameter_set_Velocity_regulator_I_gain, NULL }
                     };

/* index 0x60FB :   Mapped variable Position control parameter set */
                    UNS8 serverobject_highestSubIndex_obj60FB = 5; /* number of subindex - 1*/
                    subindex serverobject_Index60FB[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj60FB, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Position_control_parameter_set_Position_regulator_P_gain, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Position_control_parameter_set_Position_regulator_I_gain, NULL },
                       { RW, int16, sizeof (INTEGER16), (void*)&Position_control_parameter_set_Position_regulator_D_gain, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Position_control_parameter_set_Velocity_feed_forward_factor, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Position_control_parameter_set_Acceleration_feed_forward_factor, NULL }
                     };

/* index 0x60FF :   Mapped variable Target velocity */
                    subindex serverobject_Index60FF[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&Target_velocity, NULL }
                     };

/* index 0x6402 :   Mapped variable Motor type */
                    subindex serverobject_Index6402[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_type, NULL }
                     };

/* index 0x6410 :   Mapped variable Motor data */
                    UNS8 serverobject_highestSubIndex_obj6410 = 5; /* number of subindex - 1*/
                    subindex serverobject_Index6410[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&serverobject_highestSubIndex_obj6410, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_data_Continous_current_limit, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_data_Output_current_limit, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_data_Pole_pair_number, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_data_Maximal_speed_in_current_mode, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Motor_data_Thermal_time_constant_winding, NULL }
                     };

/* index 0x6502 :   Mapped variable Supported drive modes */
                    subindex serverobject_Index6502[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Supported_drive_modes, NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable serverobject_objdict[] = 
{
  { (subindex*)serverobject_Index1000,sizeof(serverobject_Index1000)/sizeof(serverobject_Index1000[0]), 0x1000},
  { (subindex*)serverobject_Index1001,sizeof(serverobject_Index1001)/sizeof(serverobject_Index1001[0]), 0x1001},
  { (subindex*)serverobject_Index1014,sizeof(serverobject_Index1014)/sizeof(serverobject_Index1014[0]), 0x1014},
  { (subindex*)serverobject_Index1016,sizeof(serverobject_Index1016)/sizeof(serverobject_Index1016[0]), 0x1016},
  { (subindex*)serverobject_Index1018,sizeof(serverobject_Index1018)/sizeof(serverobject_Index1018[0]), 0x1018},
  { (subindex*)serverobject_Index1200,sizeof(serverobject_Index1200)/sizeof(serverobject_Index1200[0]), 0x1200},
  { (subindex*)serverobject_Index1400,sizeof(serverobject_Index1400)/sizeof(serverobject_Index1400[0]), 0x1400},
  { (subindex*)serverobject_Index1401,sizeof(serverobject_Index1401)/sizeof(serverobject_Index1401[0]), 0x1401},
  { (subindex*)serverobject_Index1402,sizeof(serverobject_Index1402)/sizeof(serverobject_Index1402[0]), 0x1402},
  { (subindex*)serverobject_Index1403,sizeof(serverobject_Index1403)/sizeof(serverobject_Index1403[0]), 0x1403},
  { (subindex*)serverobject_Index1600,sizeof(serverobject_Index1600)/sizeof(serverobject_Index1600[0]), 0x1600},
  { (subindex*)serverobject_Index1601,sizeof(serverobject_Index1601)/sizeof(serverobject_Index1601[0]), 0x1601},
  { (subindex*)serverobject_Index1602,sizeof(serverobject_Index1602)/sizeof(serverobject_Index1602[0]), 0x1602},
  { (subindex*)serverobject_Index1603,sizeof(serverobject_Index1603)/sizeof(serverobject_Index1603[0]), 0x1603},
  { (subindex*)serverobject_Index1800,sizeof(serverobject_Index1800)/sizeof(serverobject_Index1800[0]), 0x1800},
  { (subindex*)serverobject_Index1801,sizeof(serverobject_Index1801)/sizeof(serverobject_Index1801[0]), 0x1801},
  { (subindex*)serverobject_Index1802,sizeof(serverobject_Index1802)/sizeof(serverobject_Index1802[0]), 0x1802},
  { (subindex*)serverobject_Index1803,sizeof(serverobject_Index1803)/sizeof(serverobject_Index1803[0]), 0x1803},
  { (subindex*)serverobject_Index1A00,sizeof(serverobject_Index1A00)/sizeof(serverobject_Index1A00[0]), 0x1A00},
  { (subindex*)serverobject_Index1A01,sizeof(serverobject_Index1A01)/sizeof(serverobject_Index1A01[0]), 0x1A01},
  { (subindex*)serverobject_Index1A02,sizeof(serverobject_Index1A02)/sizeof(serverobject_Index1A02[0]), 0x1A02},
  { (subindex*)serverobject_Index1A03,sizeof(serverobject_Index1A03)/sizeof(serverobject_Index1A03[0]), 0x1A03},
  { (subindex*)serverobject_Index6040,sizeof(serverobject_Index6040)/sizeof(serverobject_Index6040[0]), 0x6040},
  { (subindex*)serverobject_Index6041,sizeof(serverobject_Index6041)/sizeof(serverobject_Index6041[0]), 0x6041},
  { (subindex*)serverobject_Index6060,sizeof(serverobject_Index6060)/sizeof(serverobject_Index6060[0]), 0x6060},
  { (subindex*)serverobject_Index6061,sizeof(serverobject_Index6061)/sizeof(serverobject_Index6061[0]), 0x6061},
  { (subindex*)serverobject_Index6062,sizeof(serverobject_Index6062)/sizeof(serverobject_Index6062[0]), 0x6062},
  { (subindex*)serverobject_Index6064,sizeof(serverobject_Index6064)/sizeof(serverobject_Index6064[0]), 0x6064},
  { (subindex*)serverobject_Index6065,sizeof(serverobject_Index6065)/sizeof(serverobject_Index6065[0]), 0x6065},
  { (subindex*)serverobject_Index6067,sizeof(serverobject_Index6067)/sizeof(serverobject_Index6067[0]), 0x6067},
  { (subindex*)serverobject_Index6068,sizeof(serverobject_Index6068)/sizeof(serverobject_Index6068[0]), 0x6068},
  { (subindex*)serverobject_Index6069,sizeof(serverobject_Index6069)/sizeof(serverobject_Index6069[0]), 0x6069},
  { (subindex*)serverobject_Index606B,sizeof(serverobject_Index606B)/sizeof(serverobject_Index606B[0]), 0x606B},
  { (subindex*)serverobject_Index606C,sizeof(serverobject_Index606C)/sizeof(serverobject_Index606C[0]), 0x606C},
  { (subindex*)serverobject_Index6078,sizeof(serverobject_Index6078)/sizeof(serverobject_Index6078[0]), 0x6078},
  { (subindex*)serverobject_Index607A,sizeof(serverobject_Index607A)/sizeof(serverobject_Index607A[0]), 0x607A},
  { (subindex*)serverobject_Index607C,sizeof(serverobject_Index607C)/sizeof(serverobject_Index607C[0]), 0x607C},
  { (subindex*)serverobject_Index607D,sizeof(serverobject_Index607D)/sizeof(serverobject_Index607D[0]), 0x607D},
  { (subindex*)serverobject_Index607F,sizeof(serverobject_Index607F)/sizeof(serverobject_Index607F[0]), 0x607F},
  { (subindex*)serverobject_Index6081,sizeof(serverobject_Index6081)/sizeof(serverobject_Index6081[0]), 0x6081},
  { (subindex*)serverobject_Index6083,sizeof(serverobject_Index6083)/sizeof(serverobject_Index6083[0]), 0x6083},
  { (subindex*)serverobject_Index6084,sizeof(serverobject_Index6084)/sizeof(serverobject_Index6084[0]), 0x6084},
  { (subindex*)serverobject_Index6085,sizeof(serverobject_Index6085)/sizeof(serverobject_Index6085[0]), 0x6085},
  { (subindex*)serverobject_Index6086,sizeof(serverobject_Index6086)/sizeof(serverobject_Index6086[0]), 0x6086},
  { (subindex*)serverobject_Index6089,sizeof(serverobject_Index6089)/sizeof(serverobject_Index6089[0]), 0x6089},
  { (subindex*)serverobject_Index608A,sizeof(serverobject_Index608A)/sizeof(serverobject_Index608A[0]), 0x608A},
  { (subindex*)serverobject_Index608B,sizeof(serverobject_Index608B)/sizeof(serverobject_Index608B[0]), 0x608B},
  { (subindex*)serverobject_Index608C,sizeof(serverobject_Index608C)/sizeof(serverobject_Index608C[0]), 0x608C},
  { (subindex*)serverobject_Index608D,sizeof(serverobject_Index608D)/sizeof(serverobject_Index608D[0]), 0x608D},
  { (subindex*)serverobject_Index608E,sizeof(serverobject_Index608E)/sizeof(serverobject_Index608E[0]), 0x608E},
  { (subindex*)serverobject_Index6098,sizeof(serverobject_Index6098)/sizeof(serverobject_Index6098[0]), 0x6098},
  { (subindex*)serverobject_Index6099,sizeof(serverobject_Index6099)/sizeof(serverobject_Index6099[0]), 0x6099},
  { (subindex*)serverobject_Index609A,sizeof(serverobject_Index609A)/sizeof(serverobject_Index609A[0]), 0x609A},
  { (subindex*)serverobject_Index60F6,sizeof(serverobject_Index60F6)/sizeof(serverobject_Index60F6[0]), 0x60F6},
  { (subindex*)serverobject_Index60F9,sizeof(serverobject_Index60F9)/sizeof(serverobject_Index60F9[0]), 0x60F9},
  { (subindex*)serverobject_Index60FB,sizeof(serverobject_Index60FB)/sizeof(serverobject_Index60FB[0]), 0x60FB},
  { (subindex*)serverobject_Index60FF,sizeof(serverobject_Index60FF)/sizeof(serverobject_Index60FF[0]), 0x60FF},
  { (subindex*)serverobject_Index6402,sizeof(serverobject_Index6402)/sizeof(serverobject_Index6402[0]), 0x6402},
  { (subindex*)serverobject_Index6410,sizeof(serverobject_Index6410)/sizeof(serverobject_Index6410[0]), 0x6410},
  { (subindex*)serverobject_Index6502,sizeof(serverobject_Index6502)/sizeof(serverobject_Index6502[0]), 0x6502},
};

const indextable * serverobject_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1014: i = 2;break;
		case 0x1016: i = 3;break;
		case 0x1018: i = 4;break;
		case 0x1200: i = 5;break;
		case 0x1400: i = 6;break;
		case 0x1401: i = 7;break;
		case 0x1402: i = 8;break;
		case 0x1403: i = 9;break;
		case 0x1600: i = 10;break;
		case 0x1601: i = 11;break;
		case 0x1602: i = 12;break;
		case 0x1603: i = 13;break;
		case 0x1800: i = 14;break;
		case 0x1801: i = 15;break;
		case 0x1802: i = 16;break;
		case 0x1803: i = 17;break;
		case 0x1A00: i = 18;break;
		case 0x1A01: i = 19;break;
		case 0x1A02: i = 20;break;
		case 0x1A03: i = 21;break;
		case 0x6040: i = 22;break;
		case 0x6041: i = 23;break;
		case 0x6060: i = 24;break;
		case 0x6061: i = 25;break;
		case 0x6062: i = 26;break;
		case 0x6064: i = 27;break;
		case 0x6065: i = 28;break;
		case 0x6067: i = 29;break;
		case 0x6068: i = 30;break;
		case 0x6069: i = 31;break;
		case 0x606B: i = 32;break;
		case 0x606C: i = 33;break;
		case 0x6078: i = 34;break;
		case 0x607A: i = 35;break;
		case 0x607C: i = 36;break;
		case 0x607D: i = 37;break;
		case 0x607F: i = 38;break;
		case 0x6081: i = 39;break;
		case 0x6083: i = 40;break;
		case 0x6084: i = 41;break;
		case 0x6085: i = 42;break;
		case 0x6086: i = 43;break;
		case 0x6089: i = 44;break;
		case 0x608A: i = 45;break;
		case 0x608B: i = 46;break;
		case 0x608C: i = 47;break;
		case 0x608D: i = 48;break;
		case 0x608E: i = 49;break;
		case 0x6098: i = 50;break;
		case 0x6099: i = 51;break;
		case 0x609A: i = 52;break;
		case 0x60F6: i = 53;break;
		case 0x60F9: i = 54;break;
		case 0x60FB: i = 55;break;
		case 0x60FF: i = 56;break;
		case 0x6402: i = 57;break;
		case 0x6410: i = 58;break;
		case 0x6502: i = 59;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &serverobject_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status serverobject_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index serverobject_firstIndex = {
  5, /* SDO_SVR */
  0, /* SDO_CLT */
  6, /* PDO_RCV */
  10, /* PDO_RCV_MAP */
  14, /* PDO_TRS */
  18 /* PDO_TRS_MAP */
};

const quick_index serverobject_lastIndex = {
  5, /* SDO_SVR */
  0, /* SDO_CLT */
  9, /* PDO_RCV */
  13, /* PDO_RCV_MAP */
  17, /* PDO_TRS */
  21 /* PDO_TRS_MAP */
};

const UNS16 serverobject_ObjdictSize = sizeof(serverobject_objdict)/sizeof(serverobject_objdict[0]); 

CO_Data serverobject_Data = CANOPEN_NODE_DATA_INITIALIZER(serverobject);

